---
# tasks file for ansible-role-template
{% for task_name, details in cookiecutter.tasks | dictsort -%}
- name: {{ task_name }}
  {{ details['meta']['task-name'] }}: {% if 'free_form' in details['vars'].keys() -%} {{ "\"{{" }} {{ task_name}}_free_form {{ "}}\"" }} {% endif %}
  {% if 'var_keys' in details['meta'].keys() and details['meta']['var_keys'] != ['free_form'] -%}args:
    {% for arg in details['meta']['var_keys'] -%}{% if arg != 'free_form' -%}
    {{ arg }}: {{ "\"{{" }} {{ task_name }}_{{ arg }} | default({{ arg }}) }}" {% endif %}
    {% endfor %}{% endif %}
{% if "become" in details['meta'].keys() %}  become: {{ details['meta']['become'] }}{% endif %}
  ignore_errors: "{{ details['meta']['ignore_errors'] | default('yes') }}"
{% endfor %}
