---
- name: name
  hosts: {{ groups }}
{% if "become" in meta.keys() %}  become: {{ meta.become }}{% endif %}
  roles:
{% for role in roles %}    - role: {{ role.role_name }}
{% for key, var in role.vars.items() %}      {{ key }}: {{ var }}
{% endfor %}      {% if role.become != None %}become: {{ role.become }}{% endif %}
{% endfor %}
