---
- name: name
  hosts: {{ groups }}
{% if "become" in meta.keys() %}  become: {{ meta['become'] }}{% endif %}
  roles:
{% for role in roles %}    - role: {{ role.role_name }}
{% if add_role_ids %}      _role_id: {{ role.role_id }}
{% endif -%}
{% if env_id %}      _env_id: {{ env_id }}{% endif -%}
{% for key, var in role.get_vars().items() %}      {{ key }}: {{ var }}
{% endfor %}      {% if 'become' in role.get_meta().keys() %}become: {{ role.get_meta()['become'] }}{% endif %}
{% endfor %}
